name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build gem
        run: gem build asciidoctor-requirements.gemspec

      - name: Rename gem
        run: mv asciidoctor-requirements-*.gem asciidoctor-requirements.gem

      - name: Install gem
        run: gem install asciidoctor-requirements.gem

      - name: Build sample as HTML
        run: asciidoctor -r asciidoctor-diagram -r asciidoctor-requirements -a toc -a linkcss -a stylesheet=./stylesheets/requirement-style.css  samples/sample.adoc --trace

      - name: Build sample as PDF
        run: asciidoctor-pdf --theme samples/stylesheets/requirement-theme.yml -r asciidoctor-diagram -r %SCRIPT_ROOT%..\lib\asciidoctor-requirements.rb -a toc samples/sample.adoc --trace

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: samples
          path: samples
