name: Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build gem
        run: gem build asciidoctor-requirements.gemspec

      - name: Rename gem
        run: mv asciidoctor-lists-*.gem asciidoctor-lists.gem

      - name: Install gem
        run: gem install asciidoctor-requirements.gem

      - name: Build sample as HTML
        run: asciidoctor-pdf -a allow-uri-read -r asciidoctor-requirements samples/sample.adoc

      - name: Build sample as PDF
        run: asciidoctor-pdf -a allow-uri-read -r asciidoctor-requirements samples/sample.adoc

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: samples
          path: samples
